PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me all works for which there are alternate castings with a different number of interpreters (e.g. keyboard & orch / cello, oboe & orch)
# [fr] Donne-moi toutes les oeuvres pour lesquelles il existe des castings alternatifs ayant un nombre d’interprètes différent (p.ex. clavier & orch / vl, hb & orch)

SELECT DISTINCT ?expression, SAMPLE(?title) AS ?title, ?casting1, count(DISTINCT ?cDet1) AS ?n1, ?casting2, count(DISTINCT ?cDet2) as ?n2
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title ;
          mus:U13_has_casting ?casting1, ?casting2 .
  
  ?casting1 mus:U23_has_casting_detail ?cDet1 .
  
  ?casting2 mus:U23_has_casting_detail ?cDet2 .
  
  FILTER ( ?casting1 != ?casting2 )
}
GROUP BY ?expression ?casting1 ?casting2
HAVING (count(?cDet1) != count(?cDet2))

# Note: not currently in the data. See https://github.com/DOREMUS-ANR/marc2rdf/issues/22