PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the list of the works of which at least one of the dedicatees is also a performer of the work
# [fr] Donne moi la liste des oeuvres dont au moins un des dédicataires est aussi un interprète de l’oeuvre


SELECT DISTINCT ?expression, SAMPLE(?title) as ?title, ?dedicatee, ?performance
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title ;
          mus:U44_has_dedication_statement / ecrm:P67_refers_to ?dedicatee.

  ?performance efrbroo:R17_created / mus:U54_is_performed_expression_of ?expression ;
           ecrm:P9_consists_of / ecrm:P14_carried_out_by ?dedicatee .
}
