PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the list of the works of which at least one of the dedicatees is also a performer of the work
# [fr] Donne moi la liste des oeuvres dont au moins un des dédicataires est aussi un interprète de l’oeuvre


SELECT DISTINCT ?expression, SAMPLE(?title) as ?title, ?dedicatee, ?performance
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          mus:U70_has_title ?title ;
          mus:U44_has_dedication_statement / ecrm:P67_refers_to ?dedicatee.

  ?performance a efrbroo:F31_Performance ;
    efrbroo:R25_performed / ecrm:P165_incorporates ?expression ;
    ecrm:P9_consists_of / ecrm:P14_carried_out_by ?dedicatee .
}

# Note: this data are not in the db yet, but parsing can be improved. See next query

# SELECT DISTINCT ?expression, SAMPLE(?title) as ?title, ?dedication, ?dedicatee, ?performanceNote, ?performance
# WHERE {
#   ?expression a efrbroo:F22_Self-Contained_Expression ;
#           mus:U70_has_title ?title .
#   OPTIONAL {?expression mus:U44_has_dedication_statement / ecrm:P3_has_note ?dedication }
# 
#   ?performance a efrbroo:F31_Performance ;
#     efrbroo:R25_performed / ecrm:P165_incorporates ?expression ;
#     ecrm:P3_has_note ?performanceNote ;
#     ecrm:P9_consists_of / ecrm:P14_carried_out_by ?dedicatee .
# 
#   FILTER (contains(str(?dedicatee),"dédicataire"))
# }