PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the list of all symphonies that include 5 movements
# [fr] Donne moi la liste de toutes les symphonies qui comprennent 5 mouvements

SELECT DISTINCT ?work, SAMPLE(?title) as ?title
WHERE {
  ?work a efrbroo:F14_Individual_Work;
        ecrm:P148_has_component ?movements;
        efrbroo:R9_is_realised_in ?expression.
  
  ?expression rdfs:label ?title ;
            mus:U12_has_genre <http://data.doremus.org/vocabulary/iaml/genre/sy> .

} GROUP BY ?work
HAVING ( COUNT(DISTINCT ?movements) >= 5 )
LIMIT 500

# Note: they are not exactly movements