PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the list of the works that were created where they were composed
# [fr] Donne moi la liste des oeuvres qui ont été créées là où elles ont été composées

SELECT DISTINCT ?expression, SAMPLE(?title) as ?title, ?place
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title .

  ?expCreation efrbroo:R17_created ?expression ;
          ecrm:P7_took_place_at ?place .

  ?work efrbroo:R9_is_realised_in ?expression;
        mus:U5_had_premiere / ecrm:P7_took_place_at ?place .
}
LIMIT 500

# Note: we have not the composition places
