PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the flute sonatas that last less than or equal to 15 minutes
# [fr] Donne-moi les sonates pour flûte d’une durée inférieure ou égale à 15 minutes

SELECT DISTINCT ?duration , SAMPLE(?title) as ?title , ?expression
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title ;
          mus:U13_has_casting / mus:U23_has_casting_detail / mus:U2_foresees_use_of_medium_of_performance / skos:exactMatch* ?flute ;
          mus:U12_has_genre / skos:exactMatch* <http://data.doremus.org/vocabulary/iaml/genre/sn> ;
          mus:U78_estimated_duration ?duration .


  VALUES ?flute { <http://www.mimo-db.eu/InstrumentsKeywords/3955> }

  FILTER (?duration <= 900)
}

# No records found
