PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] What works are linked to a particular work and what type of link connect them?
# [fr] Quelles oeuvres sont reliées à telle oeuvre et quel type de lien les unissent ?

SELECT DISTINCT ?expression, ?link, ?expression2
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression .
  ?expression2 a efrbroo:F22_Self-Contained_Expression .

  ?work mus:U38_has_descriptive_expression | efrbroo:R9_is_realised_in ?expression .
  ?work2 mus:U38_has_descriptive_expression | efrbroo:R9_is_realised_in ?expression2 .

  { ?work ?link ?work2 } UNION { ?expression ?link ?expression }

  FILTER (?expression != ?expression2)
}
LIMIT 500
