PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the works written for oboe and orchestra after the 1900
# [fr] Donne-moi les oeuvres écrites pour hautbois et orchestre depuis 1900


SELECT DISTINCT ?start, ?expression, SAMPLE(?title) as ?title, ?casting
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title ;
          mus:U13_has_casting ?casting .

  VALUES (?oboe) { ( <http://data.doremus.org/vocabulary/iaml/mop/wob> ) ( <http://www.mimo-db.eu/InstrumentsKeywords/4164> ) }
  VALUES (?orchestra) { ( <http://data.doremus.org/vocabulary/iaml/mop/o> ) }


  ?casting mus:U23_has_casting_detail / mus:U2_foresees_use_of_medium_of_performance ?oboe .

  { ?casting mus:U23_has_casting_detail / mus:U2_foresees_use_of_medium_of_performance ?orchestra }
  UNION
  { ?casting mus:U23_has_casting_detail / mus:U2_foresees_use_of_medium_of_performance / skos:broader ?orchestra  }

  ?expCreation efrbroo:R17_created ?expression ;
          ecrm:P4_has_time-span / time:hasBeginning / time:inXSDDate ?start .

  FILTER ( ?start > "1900"^^xsd:gYear )
} ORDER BY ?start
