PREFIX mus: <http://data.doremus.org/ontology#>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# [en] Give me the works written for violin, clarinet and piano (strictly)
# [fr] Donne-moi les oeuvres écrites pour violon, clarinette et piano (strictement)


SELECT DISTINCT ?expression, SAMPLE(?title) as ?title, ?casting
WHERE {
  ?expression a efrbroo:F22_Self-Contained_Expression ;
          rdfs:label ?title ;
          mus:U13_has_casting ?casting .

  ?casting mus:U23_has_casting_detail ?allCastingDets .

  ?casting mus:U23_has_casting_detail ?castingDet1 .
  ?castingDet1 mus:U2_foresees_use_of_medium_of_performance ?violin .

  ?casting mus:U23_has_casting_detail ?castingDet2 .
  ?castingDet2 mus:U2_foresees_use_of_medium_of_performance ?clarinet.

  ?casting mus:U23_has_casting_detail ?castingDet3 .
  ?castingDet3 mus:U2_foresees_use_of_medium_of_performance  ?piano .

  VALUES (?violin) { ( <http://data.doremus.org/vocabulary/iaml/mop/svl> ) (<http://www.mimo-db.eu/InstrumentsKeywords/3573>) }
  VALUES (?clarinet) { (<http://data.doremus.org/vocabulary/iaml/mop/wcl>) (<http://www.mimo-db.eu/InstrumentsKeywords/3836>) }
  VALUES (?piano) { (<http://data.doremus.org/vocabulary/iaml/mop/kpf>) (<http://www.mimo-db.eu/InstrumentsKeywords/2299>) }
}
GROUP BY ?expression ?casting
HAVING (COUNT(?allCastingDets) = 3)
